[workspace]
members = ["crates/*"]
exclude = [
  "nix/reference-happ",
  "nix/fixtures/module-repo",
  "nix/fixtures/module-repo/zome",
]
resolver = "2"

[workspace.dependencies]
hdi = "0.5.0"
hdk = "0.4.0"
holochain = "0.4.0"
holo_hash = "0.4.0"
holochain_types = "0.4.0"
mr_bundle = "0.4.0"
