[workspace]
members = ["crates/*"]
exclude = [
  "nix/reference-happ",
  "nix/fixtures/module-repo",
  "nix/fixtures/module-repo/zome",
]
resolver = "2"

[workspace.dependencies]
hdk = "0.3"
hdi = "0.4"
holochain = "0.3"
holo_hash = "0.3"
holochain_types = "0.3"
mr_bundle = "0.3"
