name: "build-sync-npm-rev-dependencies-with-nix"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, 'main-**' ]
  pull_request: 
    branches: [ main, 'main-**' ]

jobs:
  build-sync-npm-rev-dependencies-with-nix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Build sync-npm-rev-dependencies-with-nix
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#sync-npm-rev-dependencies-with-nix 
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#sync-npm-rev-dependencies-with-nix | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Pin sync-npm-rev-dependencies-with-nix
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio sync-npm-rev-dependencies-with-nix $(nix path-info --json --accept-flake-config --no-warn-dirty .#sync-npm-rev-dependencies-with-nix | nix run nixpkgs#jq -- -r 'keys[0]')
