name: Test zome custom template
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ main, main-0.4 ]
  pull_request:
    branches: [ main, main-0.4 ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-haskell: 'true'
          root-reserve-mb: '10000'

      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Test zome template
        run: |
          nix develop --no-update-lock-file --accept-flake-config --command bash -c "sh templates/run_test_zome.sh"

