name: Test app custom template
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ main, main-0.4 ]
  pull_request:
    branches: [ main, main-0.4 ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://releases.nixos.org/nix/nix-2.24.4/install
          nix_path: nixpkgs=channel:nixos-24.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - uses: actions/checkout@v3

      - name: Test app template
        run: |
          nix develop --no-update-lock-file --accept-flake-config --command bash -c "sh templates/run_test_app.sh"

